### ISSUE TITLE
Fourmat overrides .isort.cfg when project specifies [tool.isort] configuration in pyproject.toml

### ISSUE THREAD

**Issue by ccarpita** [4Catalyzer/fourmat#27]
Modern versions of `isort` allow developers to specify configuration using a `[tool.isort]` section in `pyproject.toml`. This is preferable to prevent an over-proliferation of config file types, but `fourmat` will only see that an `.isort.cfg` file is missing and supplant its own default configuration, which takes precedence over the `pyproject.toml` configuration.

**Comment by itajaja** [comment]
that's great! I didn't know about this. when we built fourmat, isort didn't use the pyproject.toml. I'll try to find some time to work on this tomorrow

**Comment by ccarpita** [comment]
Thanks!
