### ISSUE TITLE
`fourmat fix` exits with 0 even if files were changed

### ISSUE THREAD

**Issue by sloria** [4Catalyzer/fourmat#6]
![Image 2019-05-10 16-16-17](https://user-images.githubusercontent.com/2379650/57554292-0e350380-733f-11e9-973a-13193f20ad0c.png)

This prevents us from using `pre-commit run --all-files` as the canonical linting command.

**Comment by taion** [comment]
Isn't it correct for the pre-commit hook to return 0? i.e. when committing, we want to fix things and then move on. We should only exit with 1 if there were un-fixable errors.

**Comment by sloria** [comment]
pre-commit takes a hard stance against modifying the staging area: https://github.com/pre-commit/pre-commit/issues/747#issuecomment-386782080 ¯\\_(ツ)_/¯

**Comment by sloria** [comment]
I don't strongly agree nor disagree with pre-commit's stance, but one practical side effect is that `pre-commit run...` can be encapsulate all your syntax checking commands so long as each hook exits with non-zero if files are changed.

**Comment by taion** [comment]
Erk, I mean, I know it's dangerous in principle, but in practice I've found it really convenient for stuff to get formatted for me on commit.

**Comment by sloria** [comment]
Hrm... I just checked `black`'s behavior, and it doesn't exit with an error code if it reformats, and yet the pre-commit hook *does*  fail if it reformats.

I must have done something wrong when I ran the fourmat hook earlier, but now it's doing what I expect (failing if files are formatted). So current behavior is correct. Sorry for the noise.
